### PR TITLE
Mm add fasd

### PR DESCRIPTION
**Pull request by mmaechtel**

### CODE REVIEW

**Comment by steveeJ** [comment]
Please rebase this on master

**Comment by mmaechtel** [comment]
hmm, what to reabse?

**Comment by steveeJ** [comment]
Simple rebase of this branch back on master. Something like this

```bash
git checkout master
git pull
git checkout mm-add-fasd
git rebase master
git push -f
```
Then only commits on top of the current master will be displayed in this PR. In case something needs a merge, it will say so during `git rebase master` point. 

By the way, this seems to be a good document: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by mmaechtel** [comment]
done ....

**Pull request merged**
